In [1]:
import numpy as np
import tensorflow

In [2]:
structures = np.loadtxt("structures_120k.txt")

In [3]:
structures.shape

(120000, 8)

In [4]:
structures = structures/200

In [5]:
spectra = np.loadtxt("spectra_120k.dat")

In [6]:
spectra = spectra.reshape(120000,61,4)

In [7]:
spectra.shape

(120000, 61, 4)

In [8]:
structures_train,structures_test,spec_train,spec_test = structures[:110000],structures[110000:],spectra[:110000],spectra[110000:]

In [9]:
spec_test.shape

(10000, 61, 4)

In [10]:
sample_indices = np.random.choice(len(structures_train), size=5000, replace=False)
sampled_structures = structures_train[sample_indices]
sampled_spectra = spec_train[sample_indices]


In [11]:
sampled_structures

array([[0.215, 0.88 , 0.265, ..., 0.49 , 0.555, 0.495],
       [0.14 , 0.17 , 0.59 , ..., 0.4  , 0.35 , 0.575],
       [0.45 , 0.42 , 0.77 , ..., 0.45 , 0.65 , 0.425],
       ...,
       [0.25 , 0.875, 0.96 , ..., 0.295, 0.185, 0.93 ],
       [0.915, 0.865, 0.78 , ..., 0.885, 0.145, 0.755],
       [0.92 , 0.725, 0.35 , ..., 0.99 , 0.74 , 0.245]])

In [12]:
print(sampled_structures[:5])

[[0.215 0.88  0.265 0.405 0.73  0.49  0.555 0.495]
 [0.14  0.17  0.59  0.78  0.93  0.4   0.35  0.575]
 [0.45  0.42  0.77  0.97  0.165 0.45  0.65  0.425]
 [0.335 0.275 0.545 0.7   0.52  0.25  0.41  1.   ]
 [0.145 0.885 0.205 0.135 0.24  0.77  0.975 0.715]]


In [13]:
sampled_spectra.shape

(5000, 61, 4)

In [14]:
print(sampled_spectra[:5])

[[[2.07942440e-08 1.45515166e-01 2.42447534e-15 2.22102401e-01]
  [4.39237311e-08 1.47941917e-01 7.50364362e-15 2.24318250e-01]
  [9.09656571e-08 1.50331995e-01 2.23854362e-14 2.26827888e-01]
  ...
  [3.31740481e-01 6.67964649e-01 2.45622307e-02 1.06348278e-01]
  [3.57072289e-01 6.42632841e-01 3.09301476e-02 7.94328751e-02]
  [3.91653501e-01 6.08051629e-01 3.87704727e-02 6.37061026e-02]]

 [[1.59961647e-07 2.09769414e-01 1.97821919e-13 3.06952026e-01]
  [2.95743646e-07 2.18567193e-01 4.99185543e-13 3.08300451e-01]
  [5.38554748e-07 2.30530439e-01 1.22157022e-12 3.11029753e-01]
  ...
  [1.80484921e-01 8.19220210e-01 1.46188672e-02 7.47926043e-01]
  [1.94365978e-01 8.05339152e-01 1.79586245e-02 7.29817796e-01]
  [2.06531205e-01 7.93173926e-01 2.22528640e-02 7.08104403e-01]]

 [[1.98023450e-08 2.27834407e-01 1.78099481e-15 3.34150036e-01]
  [4.47570122e-08 2.15429518e-01 6.17186995e-15 3.22225713e-01]
  [9.88684066e-08 2.03004777e-01 2.05546451e-14 3.10589447e-01]
  ...
  [4.70806786e-01 

In [15]:
model = tensorflow.keras.Sequential([
    tensorflow.keras.layers.Input(shape=(8,)),
    tensorflow.keras.layers.Dense(128, activation='elu'),

    tensorflow.keras.layers.Reshape((16, 8)),
    tensorflow.keras.layers.Conv1D(128, kernel_size=5, padding='same', activation='elu'),

    tensorflow.keras.layers.Flatten(),
    tensorflow.keras.layers.Dense(256, activation='elu'),

    tensorflow.keras.layers.Reshape((32, 8)),
    tensorflow.keras.layers.Conv1D(256, kernel_size=5, padding='same', activation='elu'),
    tensorflow.keras.layers.Flatten(),
    tensorflow.keras.layers.Dense(128, activation='elu'),

    tensorflow.keras.layers.Reshape((16, 8)),
    tensorflow.keras.layers.Conv1D(128, kernel_size=5, padding='same', activation='elu'),
    tensorflow.keras.layers.Flatten(),
    tensorflow.keras.layers.Dense(128, activation='elu'),

    tensorflow.keras.layers.Reshape((16, 8)),
    tensorflow.keras.layers.Conv1D(128, kernel_size=5, padding='same', activation='elu'),
    tensorflow.keras.layers.Flatten(),
    tensorflow.keras.layers.Dense(128, activation='elu'),

    tensorflow.keras.layers.Reshape((16, 8)),
    tensorflow.keras.layers.Conv1D(128, kernel_size=5, padding='same', activation='elu'),
    tensorflow.keras.layers.Flatten(),
    tensorflow.keras.layers.Dense(128, activation='elu'),

    tensorflow.keras.layers.Reshape((16, 8)),
    tensorflow.keras.layers.Conv1D(128, kernel_size=5, padding='same', activation='elu'),
    tensorflow.keras.layers.Flatten(),
    tensorflow.keras.layers.Dense(128, activation='elu'),

    tensorflow.keras.layers.Dense(128, activation='elu'),
    tensorflow.keras.layers.Dense(244, activation='sigmoid'),
    tensorflow.keras.layers.Reshape((61, 4)),
])

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 16, 8)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d (Conv1D)                 │ (None, 16, 128)        │         5,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │       524,544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape_1 (Reshape)             │ (None, 32, 8)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 32, 256)        │        10,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 8192)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │     1,048,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape_2 (Reshape)             │ (None, 16, 8)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 16, 128)        │         5,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 128)            │       262,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape_3 (Reshape)             │ (None, 16, 8)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 16, 128)        │         5,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │       262,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape_4 (Reshape)             │ (None, 16, 8)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_4 (Conv1D)               │ (None, 16, 128)        │         5,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 128)            │       262,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape_5 (Reshape)             │ (None, 16, 8)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_5 (Conv1D)               │ (None, 16, 128)        │         5,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 128)            │       262,27

 Total params: 2,708,212 (10.33 MB)

 Trainable params: 2,708,212 (10.33 MB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.compile(optimizer=tensorflow.keras.optimizers.Adam(learning_rate=0.001),loss='mse')

In [18]:
history =  model.fit(sampled_structures,sampled_spectra,epochs=100,batch_size=256,validation_split=0.3)


Epoch 1/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.1110 - val_loss: 0.0339
Epoch 2/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.0303 - val_loss: 0.0264
Epoch 3/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.0257 - val_loss: 0.0255
Epoch 4/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.0253 - val_loss: 0.0254
Epoch 5/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.0250 - val_loss: 0.0254
Epoch 6/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.0252 - val_loss: 0.0253
Epoch 7/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.0250 - val_loss: 0.0250
Epoch 8/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - loss: 0.0251 - val_loss: 0.0246
Epoch 9/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.0249 - val_loss: 0.0245
Epoch 10/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.0241 - val_loss: 0.0236
Epoch 11/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.0237 - val_loss: 0.0237
Epoch 12/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step

In [19]:
predicted_spectra_train = model.predict(structures_train)

3438/3438 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step


In [20]:
mse = tensorflow.keras.losses.MeanSquaredError()

loss = mse(spec_train,predicted_spectra_train).numpy()

print(f"The loss for 110k data of test1 is  {loss}")

The loss for 110k data of test1 is  0.013050858862698078


In [21]:
predicted_spectra_test = model.predict(structures_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


In [22]:
mse = tensorflow.keras.losses.MeanSquaredError()

loss = mse(spec_test,predicted_spectra_test).numpy()

print(f"The loss for 10k data of test2 is {loss}")

The loss for 10k data of test2 is 0.013117043301463127
