In [16]:
import numpy as np
import tensorflow as tf

In [17]:
structures = np.loadtxt("structures_120k.txt")

In [18]:
structures.shape

(120000, 8)

In [19]:
spectra = np.loadtxt("spectra_120k.dat")

In [20]:
spectra = spectra.reshape(120000,61,4)

In [21]:
spectra.shape

(120000, 61, 4)

In [22]:
sample_indices = np.random.choice(len(structures), size=10000, replace=False)
sampled_structures = structures[sample_indices]
sampled_spectra = spectra[sample_indices]


In [23]:
sampled_structures.shape

(10000, 8)

In [24]:
print(sampled_structures[:5])

[[ 85. 146.  37. 102.  50. 108. 159. 174.]
 [ 41.  49. 162. 117.  52. 149. 150.  44.]
 [191. 139.  66.  90. 148. 109. 127. 136.]
 [132.  70.  99. 101. 155. 140.  36. 117.]
 [ 32.  99. 178.  56. 142.  62. 156. 195.]]


In [25]:
sampled_spectra.shape

(10000, 61, 4)

In [26]:
print(sampled_spectra[:5])

[[[5.18006888e-10 1.89613455e-01 2.33080564e-18 2.96830470e-01]
  [1.28816365e-09 1.80243797e-01 9.21149069e-18 2.84886247e-01]
  [3.13809005e-09 1.71178323e-01 3.50787014e-17 2.73395792e-01]
  ...
  [8.72302976e-01 1.27402154e-01 2.68414212e-02 2.13477820e-01]
  [7.17908601e-01 2.81796530e-01 3.10036534e-02 2.42398824e-01]
  [5.71587078e-01 4.28118053e-01 3.55319849e-02 2.70356347e-01]]

 [[3.45380302e-07 1.40897792e-01 6.33429473e-13 2.28351878e-01]
  [6.73840778e-07 1.49196985e-01 1.70954579e-12 2.30588028e-01]
  [1.30037013e-06 1.57870942e-01 4.51626801e-12 2.33185567e-01]
  ...
  [2.85434118e-01 7.14271013e-01 3.68671038e-03 7.86842817e-01]
  [2.07593040e-01 7.92112090e-01 3.52255089e-03 7.95140275e-01]
  [1.59295918e-01 8.40409212e-01 3.43910776e-03 8.01783509e-01]]

 [[1.12106270e-08 8.74911048e-02 6.19409890e-16 1.63999739e-01]
  [2.49853756e-08 9.18647985e-02 2.14455242e-15 1.64801058e-01]
  [5.43084661e-08 9.88150356e-02 7.08926150e-15 1.68939822e-01]
  ...
  [9.88567234e-01 

In [27]:
model = tf.keras.models.load_model("finalmodel_15_10_2024.h5")

In [28]:
predicted_spectra = model.predict(sampled_structures)

313/313 [==============================] - 1s 3ms/step


In [29]:
mse = tf.keras.losses.MeanSquaredError()

loss = mse(sampled_spectra,predicted_spectra).numpy()

In [30]:
print(f"The loss for 10000 random data from 120k data is {loss}")

The loss for 10000 random data from 120k data is 0.5075548887252808
